apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: g0i3y5aul-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/g0i3y5aul-java-springboot-gitops